service: notification-ui

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev
plugins:
  - serverless-scriptable-plugin
  - serverless-s3-sync

custom:
  S3_BUCKET_NAME: notification-site-react-app
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts:
        - yarn install
        - yarn build
  s3Sync:
    - bucketName: ${self:custom.S3_BUCKET_NAME}
      localDir: build/

resources:
  Resources:
    StaticFilesS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_BUCKET_NAME}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticFilesS3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - "s3:ListBucket"
              Effect: "Deny"
              Principal: "*"
              Resource:
                - "Fn::Join":
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: StaticFilesS3Bucket
                      - /*
                - Fn::GetAtt: [ StaticFilesS3Bucket, Arn ]
              Condition:
                Bool:
                  aws:SecureTransport:
                    - "false"
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  [
                    "",
                    [ "arn:aws:s3:::", { "Ref": "StaticFilesS3Bucket" }, "/*" ],
                  ]
  Outputs:
    StaticFilesS3BucketName:
      Value:
        Ref: StaticFilesS3Bucket